# Project: 实验一
# Makefile created by Red Panda C++ 2.10

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
RES      = 实验一_private.res
OBJ      = elevator.o main.o $(RES)
LINKOBJ  = elevator.o main.o $(RES)
CLEANOBJ  =  elevator.o main.o 实验一_private.res 实验一.exe
LIBS     =  -s -static
INCS     =  
CXXINCS  =  
BIN      = 实验一.exe
CXXFLAGS = $(CXXINCS)  -O2 -pipe
CFLAGS   = $(INCS)  -O2 -pipe
RM       = del /q /f
WINDRESFLAGS  = 

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	-$(RM) $(CLEANOBJ) > NUL 2>&1

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

elevator.o: elevator.cpp elevator.h
	$(CPP) -c elevator.cpp -o elevator.o $(CXXFLAGS)  -finput-charset=UTF-8 -fexec-charset=gbk

main.o: main.cpp elevator.h
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)  -finput-charset=UTF-8 -fexec-charset=gbk

实验一_private.res: 实验一_private.rc 
	$(WINDRES) -i 实验一_private.rc --input-format=rc -o 实验一_private.res -O coff $(WINDRESFLAGS) 

